#!/bin/bash

# Create output file with timestamp
OUTPUT="/workspaces/mware3/src/scripts/code_backup_$(date -u +"%Y-%m-%d_%H-%M-%S").txt"

# Write header
echo "Code Output Generated at UTC: $(date -u +"%Y-%m-%d_%H-%M-%S")" > "$OUTPUT"
echo "Generated by: $USER" >> "$OUTPUT"
echo "----------------------------------------" >> "$OUTPUT"

# First add server.js and .env from root
if [ -f "/workspaces/mware3/server.js" ]; then
    echo -e "\n=== File: /workspaces/mware3/server.js ===" >> "$OUTPUT"
    cat "/workspaces/mware3/server.js" >> "$OUTPUT"
    echo "----------------------------------------" >> "$OUTPUT"
fi

if [ -f "/workspaces/mware3/.env" ]; then
    echo -e "\n=== File: /workspaces/mware3/.env ===" >> "$OUTPUT"
    cat "/workspaces/mware3/.env" >> "$OUTPUT"
    echo "----------------------------------------" >> "$OUTPUT"
fi

# Then add all files from /src
find /workspaces/mware3/src -type f -exec sh -c '
    echo -e "\n=== File: {}" >> '$OUTPUT'
    cat {} >> '$OUTPUT'
    echo "----------------------------------------" >> '$OUTPUT'
' \;

echo "Backup complete! Saved to: $OUTPUT"